const vocabulary = [
    { spanish: "hola", english: "hello", spanishSentence: "Hola, ¿cómo estás?", englishSentence: "Hello, how are you?" },
    { spanish: "adiós", english: "goodbye", spanishSentence: "Adiós, hasta mañana.", englishSentence: "Goodbye, see you tomorrow." },
    { spanish: "por favor", english: "please", spanishSentence: "Por favor, pásame la sal.", englishSentence: "Please, pass me the salt." },
    { spanish: "gracias", english: "thank you", spanishSentence: "Gracias por tu ayuda.", englishSentence: "Thank you for your help." },
    { spanish: "sí", english: "yes", spanishSentence: "Sí, quiero ir contigo.", englishSentence: "Yes, I want to go with you." },
    { spanish: "no", english: "no", spanishSentence: "No, no tengo tiempo.", englishSentence: "No, I don't have time." },
    { spanish: "agua", english: "water", spanishSentence: "Necesito un vaso de agua.", englishSentence: "I need a glass of water." },
    { spanish: "comida", english: "food", spanishSentence: "La comida está deliciosa.", englishSentence: "The food is delicious." },
    { spanish: "casa", english: "house", spanishSentence: "Mi casa es muy grande.", englishSentence: "My house is very big." },
    { spanish: "perro", english: "dog", spanishSentence: "Mi perro se llama Max.", englishSentence: "My dog is named Max." },
    { spanish: "gato", english: "cat", spanishSentence: "El gato duerme en el sofá.", englishSentence: "The cat sleeps on the sofa." },
    { spanish: "libro", english: "book", spanishSentence: "Estoy leyendo un libro interesante.", englishSentence: "I am reading an interesting book." },
    { spanish: "tiempo", english: "time/weather", spanishSentence: "No tengo tiempo para eso.", englishSentence: "I don't have time for that." },
    { spanish: "día", english: "day", spanishSentence: "Hoy es un día hermoso.", englishSentence: "Today is a beautiful day." },
    { spanish: "noche", english: "night", spanishSentence: "Buenas noches, que descanses.", englishSentence: "Good night, rest well." },
    { spanish: "amigo", english: "friend", spanishSentence: "Juan es mi mejor amigo.", englishSentence: "Juan is my best friend." },
    { spanish: "familia", english: "family", spanishSentence: "Mi familia es muy importante.", englishSentence: "My family is very important." },
    { spanish: "trabajo", english: "work", spanishSentence: "Voy al trabajo en autobús.", englishSentence: "I go to work by bus." },
    { spanish: "escuela", english: "school", spanishSentence: "Los niños van a la escuela.", englishSentence: "The children go to school." },
    { spanish: "coche", english: "car", spanishSentence: "Compré un coche nuevo.", englishSentence: "I bought a new car." },
    { spanish: "ciudad", english: "city", spanishSentence: "Vivo en una ciudad grande.", englishSentence: "I live in a big city." },
    { spanish: "país", english: "country", spanishSentence: "España es un país hermoso.", englishSentence: "Spain is a beautiful country." },
    { spanish: "mundo", english: "world", spanishSentence: "Quiero viajar por el mundo.", englishSentence: "I want to travel around the world." },
    { spanish: "amor", english: "love", spanishSentence: "El amor es importante en la vida.", englishSentence: "Love is important in life." },
    { spanish: "vida", english: "life", spanishSentence: "La vida es bella.", englishSentence: "Life is beautiful." },
    { spanish: "bueno", english: "good", spanishSentence: "Eres una persona muy buena.", englishSentence: "You are a very good person." },
    { spanish: "malo", english: "bad", spanishSentence: "Hoy tuve un día malo.", englishSentence: "I had a bad day today." },
    { spanish: "grande", english: "big", spanishSentence: "Nueva York es una ciudad grande.", englishSentence: "New York is a big city." },
    { spanish: "pequeño", english: "small", spanishSentence: "Tengo un apartamento pequeño.", englishSentence: "I have a small apartment." },
    { spanish: "nuevo", english: "new", spanishSentence: "Estrené mi teléfono nuevo.", englishSentence: "I used my new phone for the first time." },
    { spanish: "viejo", english: "old", spanishSentence: "Este edificio es muy viejo.", englishSentence: "This building is very old." },
    { spanish: "feliz", english: "happy", spanishSentence: "Estoy muy feliz hoy.", englishSentence: "I am very happy today." },
    { spanish: "triste", english: "sad", spanishSentence: "María está triste por la noticia.", englishSentence: "Maria is sad about the news." },
    { spanish: "rápido", english: "fast", spanishSentence: "El tren es muy rápido.", englishSentence: "The train is very fast." },
    { spanish: "lento", english: "slow", spanishSentence: "El tráfico es muy lento.", englishSentence: "The traffic is very slow." },
    { spanish: "comer", english: "to eat", spanishSentence: "Me gusta comer pizza.", englishSentence: "I like to eat pizza." },
    { spanish: "beber", english: "to drink", spanishSentence: "Voy a beber un café.", englishSentence: "I'm going to drink a coffee." },
    { spanish: "hablar", english: "to speak", spanishSentence: "¿Puedes hablar más despacio?", englishSentence: "Can you speak more slowly?" },
    { spanish: "escuchar", english: "to listen", spanishSentence: "Me gusta escuchar música.", englishSentence: "I like to listen to music." },
    { spanish: "ver", english: "to see", spanishSentence: "Voy a ver una película.", englishSentence: "I'm going to see a movie." },
    { spanish: "hacer", english: "to do/make", spanishSentence: "Tengo que hacer la tarea.", englishSentence: "I have to do homework." },
    { spanish: "ir", english: "to go", spanishSentence: "Voy a ir al supermercado.", englishSentence: "I'm going to go to the supermarket." },
    { spanish: "venir", english: "to come", spanishSentence: "¿Puedes venir a mi casa?", englishSentence: "Can you come to my house?" },
    { spanish: "estar", english: "to be (temporary)", spanishSentence: "Estoy cansado después del trabajo.", englishSentence: "I am tired after work." },
    { spanish: "ser", english: "to be (permanent)", spanishSentence: "Soy estudiante de español.", englishSentence: "I am a Spanish student." },
    { spanish: "tener", english: "to have", spanishSentence: "Tengo dos hermanos.", englishSentence: "I have two brothers." },
    { spanish: "querer", english: "to want", spanishSentence: "Quiero aprender español.", englishSentence: "I want to learn Spanish." },
    { spanish: "poder", english: "can/to be able to", spanishSentence: "No puedo ir a la fiesta.", englishSentence: "I can't go to the party." },
    { spanish: "saber", english: "to know (facts)", spanishSentence: "Sé hablar tres idiomas.", englishSentence: "I know how to speak three languages." },
    { spanish: "conocer", english: "to know (people/places)", spanishSentence: "Conozco bien esta ciudad.", englishSentence: "I know this city well." },
    { spanish: "padre", english: "father", spanishSentence: "Mi padre trabaja en un hospital.", englishSentence: "My father works in a hospital." },
    { spanish: "madre", english: "mother", spanishSentence: "Mi madre cocina muy bien.", englishSentence: "My mother cooks very well." },
    { spanish: "hermano", english: "brother", spanishSentence: "Tengo un hermano mayor.", englishSentence: "I have an older brother." },
    { spanish: "hermana", english: "sister", spanishSentence: "Mi hermana estudia medicina.", englishSentence: "My sister studies medicine." },
    { spanish: "hijo", english: "son", spanishSentence: "Su hijo tiene cinco años.", englishSentence: "Her son is five years old." },
    { spanish: "hija", english: "daughter", spanishSentence: "Mi hija va a la universidad.", englishSentence: "My daughter goes to university." },
    { spanish: "abuelo", english: "grandfather", spanishSentence: "Mi abuelo cuenta historias interesantes.", englishSentence: "My grandfather tells interesting stories." },
    { spanish: "abuela", english: "grandmother", spanishSentence: "Mi abuela hace galletas deliciosas.", englishSentence: "My grandmother makes delicious cookies." },
    { spanish: "esposo", english: "husband", spanishSentence: "Mi esposo es muy trabajador.", englishSentence: "My husband is very hardworking." },
    { spanish: "esposa", english: "wife", spanishSentence: "Mi esposa es doctora.", englishSentence: "My wife is a doctor." },
    { spanish: "niño", english: "child/boy", spanishSentence: "El niño juega en el parque.", englishSentence: "The boy plays in the park." },
    { spanish: "niña", english: "girl", spanishSentence: "La niña lee un cuento.", englishSentence: "The girl reads a story." },
    { spanish: "hombre", english: "man", spanishSentence: "Ese hombre es mi profesor.", englishSentence: "That man is my teacher." },
    { spanish: "mujer", english: "woman", spanishSentence: "La mujer camina por la calle.", englishSentence: "The woman walks down the street." },
    { spanish: "año", english: "year", spanishSentence: "Tengo treinta años.", englishSentence: "I am thirty years old." },
    { spanish: "mes", english: "month", spanishSentence: "Mi cumpleaños es el próximo mes.", englishSentence: "My birthday is next month." },
    { spanish: "semana", english: "week", spanishSentence: "La semana pasada estuve enfermo.", englishSentence: "Last week I was sick." },
    { spanish: "hora", english: "hour", spanishSentence: "Llevo una hora esperando.", englishSentence: "I've been waiting for an hour." },
    { spanish: "minuto", english: "minute", spanishSentence: "Espera un minuto, por favor.", englishSentence: "Wait a minute, please." },
    { spanish: "segundo", english: "second", spanishSentence: "El corredor ganó por un segundo.", englishSentence: "The runner won by a second." },
    { spanish: "mañana", english: "tomorrow/morning", spanishSentence: "Mañana voy al dentista.", englishSentence: "Tomorrow I'm going to the dentist." },
    { spanish: "tarde", english: "afternoon/late", spanishSentence: "Llegué tarde a la reunión.", englishSentence: "I arrived late to the meeting." },
    { spanish: "temprano", english: "early", spanishSentence: "Me levanto temprano todos los días.", englishSentence: "I wake up early every day." },
    { spanish: "ayer", english: "yesterday", spanishSentence: "Ayer fui al cine.", englishSentence: "Yesterday I went to the cinema." },
    { spanish: "hoy", english: "today", spanishSentence: "Hoy hace mucho calor.", englishSentence: "Today it's very hot." },
    { spanish: "ahora", english: "now", spanishSentence: "Ahora estoy ocupado.", englishSentence: "I'm busy now." },
    { spanish: "después", english: "after/later", spanishSentence: "Después de comer, voy a caminar.", englishSentence: "After eating, I'm going to walk." },
    { spanish: "antes", english: "before", spanishSentence: "Antes de salir, apaga las luces.", englishSentence: "Before leaving, turn off the lights." },
    { spanish: "siempre", english: "always", spanishSentence: "Siempre llego a tiempo.", englishSentence: "I always arrive on time." },
    { spanish: "nunca", english: "never", spanishSentence: "Nunca he estado en París.", englishSentence: "I have never been to Paris." },
    { spanish: "a veces", english: "sometimes", spanishSentence: "A veces voy al gimnasio.", englishSentence: "Sometimes I go to the gym." },
    { spanish: "mucho", english: "a lot/much", spanishSentence: "Me gusta mucho bailar.", englishSentence: "I really like to dance." },
    { spanish: "poco", english: "little/few", spanishSentence: "Tengo poco dinero.", englishSentence: "I have little money." },
    { spanish: "más", english: "more", spanishSentence: "Quiero más café, por favor.", englishSentence: "I want more coffee, please." },
    { spanish: "menos", english: "less", spanishSentence: "Necesito menos estrés en mi vida.", englishSentence: "I need less stress in my life." },
    { spanish: "muy", english: "very", spanishSentence: "Estoy muy cansado.", englishSentence: "I am very tired." },
    { spanish: "también", english: "also/too", spanishSentence: "Yo también quiero ir.", englishSentence: "I also want to go." },
    { spanish: "tampoco", english: "neither/not either", spanishSentence: "Yo tampoco sé la respuesta.", englishSentence: "I don't know the answer either." },
    { spanish: "aquí", english: "here", spanishSentence: "Aquí está tu libro.", englishSentence: "Here is your book." },
    { spanish: "allí", english: "there", spanishSentence: "El banco está allí.", englishSentence: "The bank is there." },
    { spanish: "arriba", english: "up/upstairs", spanishSentence: "Mi habitación está arriba.", englishSentence: "My room is upstairs." },
    { spanish: "abajo", english: "down/downstairs", spanishSentence: "La cocina está abajo.", englishSentence: "The kitchen is downstairs." },
    { spanish: "dentro", english: "inside", spanishSentence: "Los niños están dentro de la casa.", englishSentence: "The children are inside the house." },
    { spanish: "fuera", english: "outside", spanishSentence: "Hace frío fuera.", englishSentence: "It's cold outside." },
    { spanish: "cerca", english: "near", spanishSentence: "Vivo cerca del parque.", englishSentence: "I live near the park." },
    { spanish: "lejos", english: "far", spanishSentence: "La playa está lejos de aquí.", englishSentence: "The beach is far from here." },
    { spanish: "derecha", english: "right", spanishSentence: "Gira a la derecha en la esquina.", englishSentence: "Turn right at the corner." },
    { spanish: "izquierda", english: "left", spanishSentence: "El museo está a la izquierda.", englishSentence: "The museum is on the left." },
    { spanish: "rojo", english: "red", spanishSentence: "Me gusta tu camisa roja.", englishSentence: "I like your red shirt." },
    { spanish: "azul", english: "blue", spanishSentence: "El cielo está azul hoy.", englishSentence: "The sky is blue today." },
    { spanish: "verde", english: "green", spanishSentence: "Las hojas son verdes en verano.", englishSentence: "The leaves are green in summer." },
    { spanish: "amarillo", english: "yellow", spanishSentence: "El sol es amarillo.", englishSentence: "The sun is yellow." },
    { spanish: "negro", english: "black", spanishSentence: "Llevo zapatos negros.", englishSentence: "I wear black shoes." },
    { spanish: "blanco", english: "white", spanishSentence: "La nieve es blanca.", englishSentence: "The snow is white." },
    { spanish: "naranja", english: "orange", spanishSentence: "Las naranjas son naranjas.", englishSentence: "Oranges are orange." },
    { spanish: "rosa", english: "pink", spanishSentence: "Compré una rosa rosa.", englishSentence: "I bought a pink rose." },
    { spanish: "marrón", english: "brown", spanishSentence: "Tengo ojos marrones.", englishSentence: "I have brown eyes." },
    { spanish: "gris", english: "gray", spanishSentence: "Las nubes son grises.", englishSentence: "The clouds are gray." },
    { spanish: "color", english: "color", spanishSentence: "¿Cuál es tu color favorito?", englishSentence: "What is your favorite color?" },
    { spanish: "uno", english: "one", spanishSentence: "Tengo un hermano.", englishSentence: "I have one brother." },
    { spanish: "dos", english: "two", spanishSentence: "Necesito dos tazas de café.", englishSentence: "I need two cups of coffee." },
    { spanish: "tres", english: "three", spanishSentence: "Hay tres gatos en el jardín.", englishSentence: "There are three cats in the garden." },
    { spanish: "cuatro", english: "four", spanishSentence: "La mesa tiene cuatro patas.", englishSentence: "The table has four legs." },
    { spanish: "cinco", english: "five", spanishSentence: "Trabajo cinco días a la semana.", englishSentence: "I work five days a week." },
    { spanish: "seis", english: "six", spanishSentence: "Mi hijo tiene seis años.", englishSentence: "My son is six years old." },
    { spanish: "siete", english: "seven", spanishSentence: "Hay siete días en una semana.", englishSentence: "There are seven days in a week." },
    { spanish: "ocho", english: "eight", spanishSentence: "La clase empieza a las ocho.", englishSentence: "Class starts at eight." },
    { spanish: "nueve", english: "nine", spanishSentence: "Son las nueve de la noche.", englishSentence: "It's nine o'clock at night." },
    { spanish: "diez", english: "ten", spanishSentence: "Tengo diez dedos.", englishSentence: "I have ten fingers." },
    { spanish: "cien", english: "one hundred", spanishSentence: "Este libro tiene cien páginas.", englishSentence: "This book has one hundred pages." },
    { spanish: "mil", english: "one thousand", spanishSentence: "La ciudad tiene mil habitantes.", englishSentence: "The city has one thousand inhabitants." },
    { spanish: "pan", english: "bread", spanishSentence: "Compré pan fresco en la panadería.", englishSentence: "I bought fresh bread at the bakery." },
    { spanish: "leche", english: "milk", spanishSentence: "Bebo leche en el desayuno.", englishSentence: "I drink milk at breakfast." },
    { spanish: "carne", english: "meat", spanishSentence: "No como carne, soy vegetariano.", englishSentence: "I don't eat meat, I'm vegetarian." },
    { spanish: "pescado", english: "fish", spanishSentence: "El pescado es saludable.", englishSentence: "Fish is healthy." },
    { spanish: "fruta", english: "fruit", spanishSentence: "Me gusta comer fruta fresca.", englishSentence: "I like to eat fresh fruit." },
    { spanish: "verdura", english: "vegetable", spanishSentence: "Las verduras son buenas para la salud.", englishSentence: "Vegetables are good for health." },
    { spanish: "manzana", english: "apple", spanishSentence: "Comí una manzana verde.", englishSentence: "I ate a green apple." },
    { spanish: "naranja", english: "orange (fruit)", spanishSentence: "Hice jugo de naranja.", englishSentence: "I made orange juice." },
    { spanish: "plátano", english: "banana", spanishSentence: "Los monos comen plátanos.", englishSentence: "Monkeys eat bananas." },
    { spanish: "tomate", english: "tomato", spanishSentence: "Puse tomate en la ensalada.", englishSentence: "I put tomato in the salad." },
    { spanish: "papa", english: "potato", spanishSentence: "Las papas fritas son deliciosas.", englishSentence: "French fries are delicious." },
    { spanish: "arroz", english: "rice", spanishSentence: "El arroz es un alimento básico.", englishSentence: "Rice is a staple food." },
    { spanish: "pollo", english: "chicken", spanishSentence: "Cené pollo asado.", englishSentence: "I had roast chicken for dinner." },
    { spanish: "huevo", english: "egg", spanishSentence: "Desayuno huevos revueltos.", englishSentence: "I have scrambled eggs for breakfast." },
    { spanish: "queso", english: "cheese", spanishSentence: "Me encanta el queso manchego.", englishSentence: "I love manchego cheese." },
    { spanish: "sal", english: "salt", spanishSentence: "La sopa necesita más sal.", englishSentence: "The soup needs more salt." },
    { spanish: "azúcar", english: "sugar", spanishSentence: "¿Quieres azúcar en tu café?", englishSentence: "Do you want sugar in your coffee?" },
    { spanish: "café", english: "coffee", spanishSentence: "Tomo café todas las mañanas.", englishSentence: "I drink coffee every morning." },
    { spanish: "té", english: "tea", spanishSentence: "Prefiero el té verde.", englishSentence: "I prefer green tea." },
    { spanish: "vino", english: "wine", spanishSentence: "Bebimos vino tinto con la cena.", englishSentence: "We drank red wine with dinner." },
    { spanish: "cerveza", english: "beer", spanishSentence: "Una cerveza fría es perfecta en verano.", englishSentence: "A cold beer is perfect in summer." },
    { spanish: "jugo", english: "juice", spanishSentence: "Quiero un jugo de naranja.", englishSentence: "I want an orange juice." },
    { spanish: "mesa", english: "table", spanishSentence: "La comida está en la mesa.", englishSentence: "The food is on the table." },
    { spanish: "silla", english: "chair", spanishSentence: "Siéntate en esta silla.", englishSentence: "Sit in this chair." },
    { spanish: "cama", english: "bed", spanishSentence: "Mi cama es muy cómoda.", englishSentence: "My bed is very comfortable." },
    { spanish: "puerta", english: "door", spanishSentence: "Cierra la puerta, por favor.", englishSentence: "Close the door, please." },
    { spanish: "ventana", english: "window", spanishSentence: "Abre la ventana, hace calor.", englishSentence: "Open the window, it's hot." },
    { spanish: "cocina", english: "kitchen", spanishSentence: "Estoy cocinando en la cocina.", englishSentence: "I'm cooking in the kitchen." },
    { spanish: "baño", english: "bathroom", spanishSentence: "El baño está ocupado.", englishSentence: "The bathroom is occupied." },
    { spanish: "sala", english: "living room", spanishSentence: "Vemos televisión en la sala.", englishSentence: "We watch TV in the living room." },
    { spanish: "dormitorio", english: "bedroom", spanishSentence: "Mi dormitorio tiene dos ventanas.", englishSentence: "My bedroom has two windows." },
    { spanish: "jardín", english: "garden", spanishSentence: "Plantamos flores en el jardín.", englishSentence: "We plant flowers in the garden." },
    { spanish: "piso", english: "floor/apartment", spanishSentence: "Vivo en el tercer piso.", englishSentence: "I live on the third floor." },
    { spanish: "techo", english: "roof/ceiling", spanishSentence: "El techo está pintado de blanco.", englishSentence: "The ceiling is painted white." },
    { spanish: "pared", english: "wall", spanishSentence: "Colgué un cuadro en la pared.", englishSentence: "I hung a painting on the wall." },
    { spanish: "lámpara", english: "lamp", spanishSentence: "Enciende la lámpara, por favor.", englishSentence: "Turn on the lamp, please." },
    { spanish: "espejo", english: "mirror", spanishSentence: "Me miro en el espejo.", englishSentence: "I look at myself in the mirror." },
    { spanish: "televisión", english: "television", spanishSentence: "Veo las noticias en la televisión.", englishSentence: "I watch the news on television." },
    { spanish: "teléfono", english: "telephone", spanishSentence: "Mi teléfono está sonando.", englishSentence: "My telephone is ringing." },
    { spanish: "computadora", english: "computer", spanishSentence: "Trabajo en mi computadora.", englishSentence: "I work on my computer." },
    { spanish: "reloj", english: "clock/watch", spanishSentence: "Mi reloj marca las tres.", englishSentence: "My watch shows three o'clock." },
    { spanish: "ropa", english: "clothes", spanishSentence: "Lavé toda mi ropa.", englishSentence: "I washed all my clothes." },
    { spanish: "camisa", english: "shirt", spanishSentence: "Llevo una camisa azul.", englishSentence: "I'm wearing a blue shirt." },
    { spanish: "pantalón", english: "pants", spanishSentence: "Necesito comprar pantalones nuevos.", englishSentence: "I need to buy new pants." },
    { spanish: "zapato", english: "shoe", spanishSentence: "Estos zapatos son muy cómodos.", englishSentence: "These shoes are very comfortable." },
    { spanish: "sombrero", english: "hat", spanishSentence: "Llevo un sombrero para el sol.", englishSentence: "I wear a hat for the sun." },
    { spanish: "chaqueta", english: "jacket", spanishSentence: "Hace frío, necesito mi chaqueta.", englishSentence: "It's cold, I need my jacket." },
    { spanish: "vestido", english: "dress", spanishSentence: "Ella lleva un vestido rojo.", englishSentence: "She's wearing a red dress." },
    { spanish: "falda", english: "skirt", spanishSentence: "Compré una falda nueva.", englishSentence: "I bought a new skirt." },
    { spanish: "calcetín", english: "sock", spanishSentence: "Perdí un calcetín en la lavadora.", englishSentence: "I lost a sock in the washing machine." },
    { spanish: "cabeza", english: "head", spanishSentence: "Me duele la cabeza.", englishSentence: "My head hurts." },
    { spanish: "cara", english: "face", spanishSentence: "Me lavé la cara.", englishSentence: "I washed my face." },
    { spanish: "ojo", english: "eye", spanishSentence: "Tengo algo en el ojo.", englishSentence: "I have something in my eye." },
    { spanish: "oreja", english: "ear", spanishSentence: "Me duele la oreja.", englishSentence: "My ear hurts." },
    { spanish: "nariz", english: "nose", spanishSentence: "Tengo la nariz tapada.", englishSentence: "My nose is blocked." },
    { spanish: "boca", english: "mouth", spanishSentence: "Abre la boca, por favor.", englishSentence: "Open your mouth, please." },
    { spanish: "diente", english: "tooth", spanishSentence: "Me duele un diente.", englishSentence: "A tooth hurts." },
    { spanish: "mano", english: "hand", spanishSentence: "Dame la mano.", englishSentence: "Give me your hand." },
    { spanish: "dedo", english: "finger", spanishSentence: "Me corté el dedo.", englishSentence: "I cut my finger." },
    { spanish: "pie", english: "foot", spanishSentence: "Me duele el pie derecho.", englishSentence: "My right foot hurts." },
    { spanish: "pierna", english: "leg", spanishSentence: "Me rompí la pierna.", englishSentence: "I broke my leg." },
    { spanish: "brazo", english: "arm", spanishSentence: "Levanta el brazo.", englishSentence: "Raise your arm." },
    { spanish: "espalda", english: "back", spanishSentence: "Me duele la espalda.", englishSentence: "My back hurts." },
    { spanish: "estómago", english: "stomach", spanishSentence: "Tengo dolor de estómago.", englishSentence: "I have a stomachache." },
    { spanish: "corazón", english: "heart", spanishSentence: "Mi corazón late rápido.", englishSentence: "My heart beats fast." },
    { spanish: "sol", english: "sun", spanishSentence: "El sol brilla hoy.", englishSentence: "The sun is shining today." },
    { spanish: "luna", english: "moon", spanishSentence: "La luna está llena esta noche.", englishSentence: "The moon is full tonight." },
    { spanish: "estrella", english: "star", spanishSentence: "Las estrellas brillan en el cielo.", englishSentence: "The stars shine in the sky." },
    { spanish: "cielo", english: "sky", spanishSentence: "El cielo está despejado.", englishSentence: "The sky is clear." },
    { spanish: "nube", english: "cloud", spanishSentence: "Hay muchas nubes hoy.", englishSentence: "There are many clouds today." },
    { spanish: "lluvia", english: "rain", spanishSentence: "Está cayendo lluvia.", englishSentence: "Rain is falling." },
    { spanish: "nieve", english: "snow", spanishSentence: "La nieve cubre las montañas.", englishSentence: "Snow covers the mountains." },
    { spanish: "viento", english: "wind", spanishSentence: "Hace mucho viento hoy.", englishSentence: "It's very windy today." },
    { spanish: "calor", english: "heat", spanishSentence: "No soporto el calor del verano.", englishSentence: "I can't stand the summer heat." },
    { spanish: "frío", english: "cold", spanishSentence: "Tengo mucho frío.", englishSentence: "I'm very cold." },
    { spanish: "playa", english: "beach", spanishSentence: "Vamos a la playa mañana.", englishSentence: "We're going to the beach tomorrow." },
    { spanish: "montaña", english: "mountain", spanishSentence: "Subimos la montaña.", englishSentence: "We climbed the mountain." },
    { spanish: "río", english: "river", spanishSentence: "El río es muy ancho.", englishSentence: "The river is very wide." },
    { spanish: "mar", english: "sea", spanishSentence: "Me gusta nadar en el mar.", englishSentence: "I like to swim in the sea." },
    { spanish: "árbol", english: "tree", spanishSentence: "Hay un árbol grande en el parque.", englishSentence: "There is a big tree in the park." },
    { spanish: "flor", english: "flower", spanishSentence: "Las flores huelen bien.", englishSentence: "The flowers smell good." },
    { spanish: "hierba", english: "grass", spanishSentence: "La hierba está verde.", englishSentence: "The grass is green." },
    { spanish: "piedra", english: "stone", spanishSentence: "Encontré una piedra bonita.", englishSentence: "I found a pretty stone." },
    { spanish: "fuego", english: "fire", spanishSentence: "El fuego nos da calor.", englishSentence: "The fire gives us warmth." },
    { spanish: "tierra", english: "earth/soil", spanishSentence: "Plantamos las semillas en la tierra.", englishSentence: "We plant the seeds in the soil." }
];
